// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_qeaVf4Eq0N1jzNVHzZcmp30Nl48xu8',
    appId: '1:463316457684:web:189b5a4871416839784341',
    messagingSenderId: '463316457684',
    projectId: 'video-1d77d',
    authDomain: 'video-1d77d.firebaseapp.com',
    storageBucket: 'video-1d77d.firebasestorage.app',
    measurementId: 'G-PL6WH6JZ05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqAnUFK6BZs-NsirQ_nX6VSg98jhjC0bI',
    appId: '1:463316457684:android:e352cd90d62a9580784341',
    messagingSenderId: '463316457684',
    projectId: 'video-1d77d',
    storageBucket: 'video-1d77d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd0ETN-UvKwrzuRVYSJuIR2jUSnWb_uqQ',
    appId: '1:463316457684:ios:6f03648bbd80f1fe784341',
    messagingSenderId: '463316457684',
    projectId: 'video-1d77d',
    storageBucket: 'video-1d77d.firebasestorage.app',
    androidClientId: '463316457684-rro1c9gughdl3fjtmhd4dtbdbhvad6cq.apps.googleusercontent.com',
    iosClientId: '463316457684-l2iku90q103rqlmr9mckgnrf4eqganlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.videotiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd0ETN-UvKwrzuRVYSJuIR2jUSnWb_uqQ',
    appId: '1:463316457684:ios:6f03648bbd80f1fe784341',
    messagingSenderId: '463316457684',
    projectId: 'video-1d77d',
    storageBucket: 'video-1d77d.firebasestorage.app',
    androidClientId: '463316457684-rro1c9gughdl3fjtmhd4dtbdbhvad6cq.apps.googleusercontent.com',
    iosClientId: '463316457684-l2iku90q103rqlmr9mckgnrf4eqganlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.videotiktok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_qeaVf4Eq0N1jzNVHzZcmp30Nl48xu8',
    appId: '1:463316457684:web:54000815b1b2f208784341',
    messagingSenderId: '463316457684',
    projectId: 'video-1d77d',
    authDomain: 'video-1d77d.firebaseapp.com',
    storageBucket: 'video-1d77d.firebasestorage.app',
    measurementId: 'G-4BXGSGG7L9',
  );
}
